List<String> globalMedicationList() {
  final List<String> medications = [
    'Abilify',
    'Abilify Asimtufii',
    'Abilify Maintena',
    'Abiraterone',
    'Acetaminophen',
    'Acetylcysteine',
    'Actemra',
    'Acyclovir',
    'Adalimumab',
    'Adderall',
    'Adderall XR',
    'Advair Diskus',
    'Advil',
    'Afinitor',
    'Agamree',
    'Aimovig',
    'Ajovy',
    'Albuterol',
    'Aldactone',
    'Alecensa',
    'Alendronate',
    'Aleve',
    'Alfuzosin',
    'Allegra',
    'Allopurinol',
    'Alprazolam',
    'Alprolix',
    'Alunbrig',
    'Amantadine',
    'Ambien',
    'Ambroxol',
    'Amiodarone',
    'Amitriptyline',
    'Amlodipine',
    'Amoxicillin',
    'Amoxicillin and Clavulanate',
    'Ampicillin',
    'Anastrozole',
    'AndroGel',
    'Annovera',
    'Apalutamide',
    'Apixaban',
    'Apokyn',
    'Apriso',
    'Aptiom',
    'Arikayce',
    'Arimidex',
    'Aripiprazole',
    'Aristada',
    'Aromasin',
    'Ascorbic acid',
    'Aspirin',
    'Atarax',
    'Atenolol',
    'Ativan',
    'Atogepant',
    'Atomoxetine',
    'Atorvastatin',
    'Aubagio',
    'Augmentin',
    'Austedo',
    'Auvelity',
    'Avonex',
    'Avsola',
    'Azathioprine',
    'Azelastine',
    'Azilect',
    'Azithromycin',
    'Azulfidine',
    'Bacitracin',
    'Bacitracin topical',
    'Baclofen',
    'Bactrim',
    'Bactroban',
    'Balsalazide',
    'Banzel',
    'Baqsimi',
    'Basaglar',
    'Bavencio',
    'Belsomra',
    'Benadryl',
    'Benazepril',
    'Bendeka',
    'Benicar',
    'Benlysta',
    'Bentyl',
    'Benzonatate',
    'Benztropine',
    'Berinert',
    'Betadine',
    'Betamethasone',
    'Betaseron',
    'Bevacizumab',
    'Beyfortus',
    'Bicalutamide',
    'Bictegravir/Emtricitabine/Tenofovir Alafenamide',
    'Biktarvy',
    'Biotin',
    'Bisacodyl',
    'Bisoprolol',
    'Blincyto',
    'Boniva',
    'Botox',
    'Breo Ellipta',
    'Brexpiprazole',
    'Breyanzi',
    'Breztri Aerosphere',
    'Brilinta',
    'Brimonidine',
    'Briumvi',
    'Briviact',
    'Bromfed DM',
    'Brukinsa',
    'Bryhali',
    'Budesonide',
    'Budesonide and formoterol',
    'Bumetanide',
    'Bumex',
    'Bunavail',
    'Buprenex',
    'Buprenorphine',
    'Buprenorphine/naloxone',
    'Bupropion',
    'Buspar',
    'Buspirone',
    'Bystolic',
    'Cabenuva',
    'Cabometyx',
    'Calcitriol',
    'Calcium carbonate',
    'Calquence',
    'Canasa',
    'Candesartan',
    'Caplyta',
    'Captopril',
    'Carbamazepine',
    'Carbidopa and levodopa',
    'Carvedilol',
    'Carvykti',
    'Casodex',
    'Cefdinir',
    'Cefixime',
    'Ceftriaxone',
    'Cefuroxime',
    'Celebrex',
    'Celecoxib',
    'Celexa',
    'Cephalexin',
    'Cequa',
    'Cetirizine',
    'Chlorpheniramine',
    'Chlorthalidone',
    'Cholecalciferol',
    'Cialis',
    'Cimzia',
    'Cinryze',
    'Cipro',
    'Ciprofloxacin',
    'Citalopram',
    'Clarithromycin',
    'Claritin',
    'Clindamycin',
    'Clobetasol',
    'Clobex',
    'Clodan',
    'Clonazepam',
    'Clonidine',
    'Clopidogrel',
    'Clotrimazole',
    'Clozapine',
    'Codeine',
    'Colace',
    'Colazal',
    'Colchicine',
    'Concerta',
    'Coreg',
    'Cosentyx',
    'Crestor',
    'Cyanocobalamin',
    'Cyclobenzaprine',
    'Cymbalta',
    'Dabigatran',
    'Dapagliflozin',
    'Darzalex',
    'Dayvigo',
    'Decadron',
    'Degarelix',
    'Delzicol',
    'Depakote',
    'Descovy',
    'Desloratadine',
    'Desmopressin',
    'Desvenlafaxine',
    'Desyrel',
    'Dexamethasone',
    'Dexamethasone Intensol',
    'Dextroamphetamine',
    'Dextromethorphan',
    'Dextrose',
    'Diacomit',
    'Diastat',
    'Diazepam',
    'Diclofenac',
    'Dicyclomine',
    'Diflucan',
    'Digoxin',
    'Dilantin',
    'Dilaudid',
    'Diltiazem',
    'Diovan',
    'Dipentum',
    'Diphenhydramine',
    'Diprolene',
    'Divalproex',
    'Divalproex sodium',
    'Docusate Sodium',
    'Donepezil',
    'Doxazosin',
    'Doxepin',
    'Doxorubicin',
    'Doxycycline',
    'Doxycycline Hyclate',
    'Doxylamine',
    'Dramamine',
    'Dulaglutide',
    'Dulcolax',
    'Duloxetine',
    'Duopa',
    'Dupixent',
    'Dutasteride',
    'Edoxaban',
    'Effexor',
    'Effexor XR',
    'Elagolix',
    'Elavil',
    'Eletriptan',
    'Eligard',
    'Eliquis',
    'Emgality',
    'Empagliflozin',
    'Empaveli',
    'Emtricitabine',
    'Enalapril',
    'Enbrel',
    'Enhertu',
    'Enoxaparin',
    'Entecavir',
    'Entresto',
    'Entyvio',
    'Epclusa',
    'Epidiolex',
    'Epinephrine',
    'EpiPen',
    'Eplerenone',
    'Ergocalciferol',
    'Erleada',
    'Ertapenem',
    'Erythromycin',
    'Erythromycin ophthalmic',
    'Escitalopram',
    'Esomeprazole',
    'Estrace',
    'Estradiol',
    'Eszopiclone',
    'Etanercept',
    'Ethambutol',
    'Ethosuximide',
    'Etodolac',
    'Etoposide',
    'Eulexin',
    'Euthyrox',
    'Evenity',
    'Evista',
    'Evkeeza',
    'Evusheld',
    'Excedrin',
    'Exemestane',
    'Extavia',
    'Eysuvis',
    'Ezetimibe',
    'Famotidine',
    'Farxiga',
    'Fasenra',
    'Faslodex',
    'Febuxostat',
    'Felodipine',
    'Femara',
    'Fenofibrate',
    'Fentanyl',
    'FeroSul',
    'Ferrous gluconate',
    'Ferrous Sulfate',
    'Fexofenadine',
    'Fiasp',
    'Finasteride',
    'Fintepla',
    'Fioricet',
    'Firazyr',
    'Firmagon',
    'Fish Oil',
    'Flagyl',
    'Flecainide',
    'Flexeril',
    'Flomax',
    'Flonase',
    'Flonase Allergy Relief',
    'Flovent',
    'Flovent HFA',
    'Fluconazole',
    'Fludrocortisone',
    'FluMist Vaccine',
    'Fluocinonide',
    'Fluorouracil',
    'Fluoxetine',
    'Fluphenazine',
    'Flutamide',
    'Fluticasone',
    'Fluticasone and salmeterol',
    'Fluticasone nasal',
    'Fluvoxamine',
    'Focalin',
    'Folic Acid',
    'Formoterol',
    'Forteo',
    'Fosamax',
    'Fosfomycin',
    'Fulvestrant',
    'Furosemide',
    'Fycompa',
    'Gabapentin',
    'Gabapentin enacarbil',
    'Galantamine',
    'Galcanezumab',
    'Ganciclovir',
    'Garlic',
    'Gas-X',
    'GaviLyte G',
    'Gaviscon',
    'Gavreto',
    'Gazyva',
    'Gemcitabine',
    'Gemfibrozil',
    'Gemtesa',
    'Gemzar',
    'Genotropin',
    'Gentamicin',
    'Genvoya',
    'Geodon',
    'Giazo',
    'Gilenya',
    'Ginkgo Biloba',
    'Ginseng',
    'Glatiramer',
    'Gleevec',
    'Glimepiride',
    'Glipizide',
    'Glucagon',
    'Glucophage',
    'Glucosamine',
    'Glucotrol',
    'Glutathione',
    'Glyburide',
    'Glycerin',
    'GlycoLax',
    'Glycopyrrolate',
    'Glyxambi',
    'Gocovri',
    'GoLYTELY',
    'Goserelin',
    'Granisetron',
    'Griseofulvin',
    'Guaifenesin',
    'Guanfacine',
    'Gvoke HypoPen',
    'Hadlima',
    'Haegarda',
    'Halcion',
    'Haldol',
    'Halobetasol',
    'Haloperidol',
    'Harvoni',
    'Hemgenix',
    'Heparin',
    'Hepatitis B adult vaccine',
    'Herceptin',
    'Hibiclens',
    'Hiprex',
    'Histrelin',
    'Hizentra',
    'Horizant',
    'Humalog',
    'Humalog Mix 75/25',
    'Humira',
    'Humulin N',
    'Humulin R',
    'Humulin RU 500',
    'Hydralazine',
    'Hydrea',
    'Hydrochlorothiazide',
    'Hydrochlorothiazide and irbesartan',
    'Hydrochlorothiazide and lisinopril',
    'Hydrochlorothiazide and losartan',
    'Hydrochlorothiazide and triamterene',
    'Hydrochlorothiazide and valsartan',
    'Hydrocodone',
    'Hydrocodone and Acetaminophen',
    'Hydrocodone and ibuprofen',
    'Hydrocortisone',
    'Hydrocortisone topical',
    'Hydromorphone',
    'Hydroxychloroquine',
    'Hydroxyurea',
    'Hydroxyzine',
    'Hydroxyzine Pamoate',
    'Hyoscyamine',
    'Hyrimoz',
    'Hytrin',
    'Hyzaar',
    'Ibandronate',
    'Ibrance',
    'Ibu',
    'Ibuprofen',
    'Iclusig',
    'Icosapent',
    'Idhifa',
    'Ilumya',
    'Imatinib',
    'Imbruvica',
    'Imdur',
    'Imfinzi',
    'Imipramine',
    'Imiquimod',
    'Imitrex',
    'Imodium',
    'Imodium A-D',
    'Impoyz',
    'Imuran',
    'Inbrija',
    'Incruse Ellipta',
    'Indapamide',
    'Inderal',
    'Indocin',
    'Indomethacin',
    'Infed',
    'Inflectra',
    'Infliximab',
    'Ingrezza',
    'Injectafer',
    'Inlyta',
    'Inrebic',
    'Insulin Aspart',
    'Insulin Detemir',
    'Insulin Glargine',
    'Insulin Lispro',
    'Insulin Regular',
    'Intuniv',
    'Invega',
    'Invega Sustenna',
    'Invokana',
    'Iopamidol',
    'Ipratropium',
    'Irbesartan',
    'Isoniazid',
    'Isosorbide',
    'Isosorbide dinitrate',
    'Isosorbide Mononitrate',
    'Isotretinoin',
    'Itraconazole',
    'Ivabradine',
    'Ivermectin',
    'Jackass Bitters',
    'Jadenu',
    'Jaimiess',
    'Jakafi',
    'Jalyn',
    'Jantoven',
    'Janumet',
    'Janumet XR',
    'Januvia',
    'Japanese Knotweed',
    'Jardiance',
    'Jasmiel',
    'Jatenzo',
    'Javygtor',
    'Jaypirca',
    'Jelmyto',
    'Jemperli',
    'Jencycla',
    'Jentadueto',
    'Jentadueto XR',
    'Jesduvroq',
    'Jeuveau',
    'Jevtana',
    'Jinteli',
    'Jivi',
    'Joenja',
    'Jolessa',
    'Jornay PM',
    'Joyeaux',
    'Jubbonti',
    'Jublia',
    'Juluca',
    'Junel',
    'Junel 1.5/30',
    'Junel 1/20',
    'Junel Fe 24',
    'Juvederm',
    'Juxtapid',
    'Jylamvo',
    'Jynarque',
    'K-Dur',
    'Kadcyla',
    'Kadian',
    'kalbitor',
    'Kanamycin',
    'Kaopectate',
    'Kapvay',
    'Kariva',
    'Kava',
    'Kayexalate',
    'Keflex',
    'Kenalog',
    'Kenalog-40',
    'Keppra',
    'Keppra XR',
    'Kerendia',
    'Kesimpta',
    'Ketalar',
    'Ketamine',
    'Ketoconazole',
    'Ketoconazole Shampoo',
    'Ketoconazole topical',
    'Ketoprofen',
    'Ketorolac',
    'Ketorolac ophthalmic',
    'Ketorolac Tromethamine',
    'Ketotifen',
    'Ketotifen ophthalmic',
    'Kevzara',
    'Keytruda',
    'Kineret',
    'Kisqali',
    'Klonopin',
    'Klor-Con',
    'Kratom',
    'Krill Oil',
    'Krystexxa',
    'Kurvelo',
    'Kyleena',
    'Kymriah',
    'Kynmobi',
    'Kyprolis',
    'Labetalol',
    'Lacosamide',
    'Lactulose',
    'Lamictal',
    'Lamotrigine',
    'Lanadelumab',
    'Lansoprazole',
    'Lantus',
    'Lasix',
    'Latanoprost',
    'Latuda',
    'Leflunomide',
    'Lenvatinib',
    'Lenvima',
    'Leqembi',
    'Letrozole',
    'Leukeran',
    'Leuprolide',
    'Levalbuterol',
    'Levaquin',
    'Levemir',
    'Levetiracetam',
    'Levocetirizine',
    'Levodopa',
    'Levofloxacin',
    'Levonorgestrel',
    'Levothyroxine',
    'Lexapro',
    'Lexette',
    'Lialda',
    'Lidex',
    'Lidocaine',
    'Liletta',
    'Linezolid',
    'Linzess',
    'Lipitor',
    'Liraglutide',
    'Lisdexamfetamine',
    'Lisinopril',
    'Lithium',
    'Loestrin 24 Fe',
    'Lofexidine',
    'Lokelma',
    'Lomotil',
    'Loperamide',
    'Lopressor',
    'Loratadine',
    'Lorazepam',
    'Lorlatinib',
    'Losartan',
    'Lovastatin',
    'Lovenox',
    'Lunesta',
    'Lupron Depot',
    'Lurasidone',
    'Luxiq',
    'Lyrica',
    'Lyumjev',
    'Macrobid',
    'Magnesium oxide',
    'Magnesium sulfate',
    'Mavenclad',
    'Mavyret',
    'Mayzent',
    'Meclizine',
    'Medrol',
    'Medroxyprogesterone',
    'Melatonin',
    'Meloxicam',
    'Memantine',
    'Meropenem',
    'Mesalamine',
    'Metformin',
    'Methadone',
    'Methimazole',
    'Methocarbamol',
    'Methotrexate',
    'Methylphenidate',
    'Methylprednisolone',
    'Metoclopramide',
    'Metoprolol',
    'Metronidazole',
    'Midazolam',
    'Midodrine',
    'Minocycline',
    'Minoxidil',
    'MiraLAX',
    'Mirtazapine',
    'Misoprostol',
    'Mobic',
    'Modafinil',
    'Montelukast',
    'Morphine',
    'Motrin',
    'Mounjaro',
    'Moxifloxacin',
    'Mucinex',
    'Mupirocin',
    'Mupirocin topical',
    'Mycapssa',
    'Mycophenolate mofetil',
    'Myfembree',
    'Mylotarg',
    'Myrbetriq',
    'Nabumetone',
    'NAC',
    'Nadolol',
    'Naloxone',
    'Naltrexone',
    'Namenda',
    'Naprosyn',
    'Naproxen',
    'Naratriptan',
    'Narcan',
    'Nasacort',
    'Nasonex 24HR Allergy',
    'Nayzilam',
    'Nebivolol',
    'Neomycin',
    'Neosporin',
    'Nerlynx',
    'Neupro',
    'Neurontin',
    'Nexium',
    'Nexletol',
    'Nexlizet',
    'Nexplanon',
    'Niacin',
    'Nicardipine',
    'Nicotine',
    'Nifedipine',
    'Nilandron',
    'Nilutamide',
    'Ninlaro',
    'Nitrofurantoin',
    'Nitroglycerin',
    'Nitrostat',
    'Nivolumab',
    'Norco',
    'Norepinephrine',
    'Norethindrone',
    'Norflex',
    'Nortriptyline',
    'Norvasc',
    'Nourianz',
    'Novolin N',
    'NovoLog',
    'NP Thyroid',
    'NPlate',
    'Nubeqa',
    'Nucala',
    'Nurtec ODT',
    'Nuvigil',
    'Nystatin',
    'Ocella',
    'Ocrelizumab',
    'Ocrevus',
    'Octreotide',
    'Odefsey',
    'Ofev',
    'Ofloxacin',
    'Ofloxacin ophthalmic',
    'Ojjaara',
    'Olanzapine',
    'Olaparib',
    'Olmesartan',
    'Olopatadine',
    'Olopatadine ophthalmic',
    'Olux',
    'Omalizumab',
    'Omega-3',
    'Omeprazole',
    'Omnicef',
    'Omnipaque 350',
    'Ondansetron',
    'Onfi',
    'Ongentys',
    'Onureg',
    'Opcon-A',
    'Opdivo',
    'Opill',
    'Opzelura',
    'Orencia',
    'Orgovyx',
    'Oriahnn',
    'Orladeyo',
    'Orlistat',
    'Orphenadrine',
    'Ortho Tri-Cyclen',
    'Oseltamivir',
    'Osimertinib',
    'Otezla',
    'Oxaliplatin',
    'Oxazepam',
    'Oxcarbazepine',
    'Oxtella XR',
    'Oxybutynin',
    'Oxycodone',
    'Oxycontin',
    'Oxygen',
    'Oxymetazoline',
    'Oxymetazoline nasal',
    'Oxytocin',
    'Ozanimod',
    'Ozempic',
    'Pantoprazole',
    'Paracetamol',
    'Paragard',
    'Paroxetine',
    'Paxil',
    'Paxlovid',
    'Pentasa',
    'Pepcid',
    'Percocet',
    'Phenazopyridine',
    'Phenergan',
    'Phenobarbital',
    'Phentermine',
    'Phenylephrine',
    'Phenytoin',
    'Phexxi',
    'Pioglitazone',
    'Piperacillin and tazobactam',
    'Plan B',
    'Plaquenil',
    'Plavix',
    'Polyethylene glycol 3350',
    'Potassium Chloride',
    'Pradaxa',
    'Praluent',
    'Pramipexole',
    'Pravastatin',
    'Prazosin',
    'Prednisolone',
    'Prednisone',
    'Pregabalin',
    'Premarin',
    'Prilosec',
    'Primidone',
    'Pristiq',
    'ProAir HFA',
    'Probuphine',
    'Prochlorperazine',
    'Progesterone',
    'Prolia',
    'Promacta',
    'Promethazine',
    'Propranolol',
    'Protonix',
    'Provenge',
    'Provigil',
    'Prozac',
    'Pseudoephedrine',
    'Pyridium',
    'Qalsody',
    'Qbrelis',
    'Qbrexza',
    'Qelbree',
    'QNASL',
    'Qsymia',
    'Qtern',
    'Quadramet',
    'Qualaquin',
    'Quassia',
    'Quazepam',
    'Quelicin',
    'Quercetin',
    'Questran',
    'Quetiapine',
    'QuilliChew ER',
    'Quillivant XR',
    'Quinapril',
    'Quinidine',
    'Quinine',
    'Quizartinib',
    'Qulipta',
    'Qutenza',
    'Quviviq',
    'Qvar',
    'Qvar Redihaler',
    'Rabeprazole',
    'Raloxifene',
    'Ramelteon',
    'Ramipril',
    'Ranexa',
    'Ranitidine',
    'Ranolazine',
    'Rapamune',
    'Rebif',
    'Reclast',
    'Reglan',
    'Relafen',
    'Relugolix',
    'Remdesivir',
    'Remeron',
    'Remicade',
    'Renflexis',
    'Repaglinide',
    'Repatha',
    'Requip',
    'Restasis',
    'Restoril',
    'Retevmo',
    'Revlimid',
    'Rexulti',
    'Reyvow',
    'Rifampin',
    'Rifaximin',
    'Rimegepant',
    'Rinvoq',
    'Risdiplam',
    'Risedronate',
    'Risperdal',
    'Risperidone',
    'Ritalin',
    'Rituxan',
    'Rituxan Hycela',
    'Rituximab',
    'Rivaroxaban',
    'Rivastigmine',
    'Rizatriptan',
    'Robaxin',
    'Robitussin',
    'Rocephin',
    'Ropinirole',
    'Rosuvastatin',
    'Rowasa',
    'Roxicodone',
    'Ruconest',
    'Rybelsus',
    'Rydapt',
    'Rytary',
    'Sabril',
    'Sacubitril and valsartan',
    'Salbutamol',
    'Salmeterol',
    'Sandostatin',
    'Saphnelo',
    'Saw Palmetto',
    'Saxenda',
    'Scopolamine',
    'Semaglutide',
    'Senna',
    'Senokot',
    'Sernivo',
    'Seroquel',
    'Sertraline',
    'Sevelamer',
    'Shingrix',
    'Sildenafil',
    'Simethicone',
    'Simponi',
    'Simvastatin',
    'Sinemet',
    'Singulair',
    'Sitagliptin',
    'Skyrizi',
    'Sodium bicarbonate',
    'Sodium Chloride',
    'Sofosbuvir',
    'Solifenacin',
    'Soliqua',
    'Soliris',
    'SoluMEDROL',
    'Soma',
    'Somatuline Depot',
    'Somavert',
    'Sotalol',
    'Sovaldi',
    'Spinraza',
    'Spiriva',
    'Spironolactone',
    'Sprycel',
    'Stelara',
    'Strattera',
    'Stribild',
    'Sublocade',
    'Suboxone',
    'Sucralfate',
    'Sudafed',
    'Sulfamethoxazole and trimethoprim',
    'Sulfasalazine',
    'Sumatriptan',
    'Sunosi',
    'Supprelin LA',
    'Sutent',
    'Syfovre',
    'Symbicort',
    'Sympazan',
    'Synjardy',
    'Synthroid',
    'Tacrolimus',
    'Tadalafil',
    'Takhzyro',
    'Taltz',
    'Tamiflu',
    'Tamoxifen',
    'Tamsulosin',
    'Tazarotene',
    'Tazorac',
    'Tecartus',
    'Tecentriq',
    'Tecfidera',
    'Tecvayli',
    'Tegretol',
    'Telmisartan',
    'Temazepam',
    'Temovate',
    'Tenofovir',
    'Tenormin',
    'Tepezza',
    'Terazosin',
    'Terbinafine',
    'Testosterone',
    'Tetracycline',
    'Theophylline',
    'Thiamine',
    'Tibsovo',
    'Timolol',
    'Tiotropium',
    'Tirzepatide',
    'Tizanidine',
    'Topamax',
    'Topiramate',
    'Toprol XL',
    'Toradol',
    'Torsemide',
    'Toujeo',
    'Tradjenta',
    'Tramadol',
    'Tranexamic acid',
    'Trazodone',
    'Treanda',
    'Trelegy Ellipta',
    'Trelstar',
    'Tremfya',
    'Tresiba',
    'Tretinoin',
    'Triamcinolone',
    'Triamterene',
    'Trileptal',
    'Trintellix',
    'Triptorelin',
    'Triumeq',
    'Trokendi XR',
    'Trulicity',
    'Truqap',
    'Truxima',
    'Twirla',
    'Tylenol',
    'Tyrvaya',
    'Tysabri',
    'Ubiquinone',
    'Ublituximab',
    'Ubrelvy',
    'Ubrogepant',
    'Uceris',
    'Udenyca',
    'Ulipristal',
    'Uloric',
    'Ulspira',
    'Ultomiris',
    'Ultracet',
    'Ultram',
    'Ultravate',
    'Umeclidinium',
    'Umeclidinium and vilanterol',
    'Unasyn',
    'Uniphyl',
    'Unisom',
    'Unisom Sleep Gels',
    'Unithroid',
    'Upadacitinib',
    'Uplizna',
    'Upneeq',
    'Uptravi',
    'Urea',
    'Urea Cream',
    'Urea topical',
    'Urecholine',
    'Uribel',
    'Urispas',
    'Uristat',
    'Uro-MP',
    'Urocit-K',
    'Urogesic-Blue',
    'Uroxatral',
    'Urso',
    'Urso Forte',
    'Ursodiol',
    'Ustekinumab',
    'Uzedy',
    'Valacyclovir',
    'Valium',
    'Valproate Sodium',
    'Valproic acid',
    'Valsartan',
    'Valtoco',
    'Valtrex',
    'Vancomycin',
    'Vanos',
    'Varenicline',
    'Vascepa',
    'Vasopressin',
    'Velcade',
    'Venclexta',
    'Venlafaxine',
    'Venofer',
    'Ventolin',
    'Ventolin HFA',
    'Veozah',
    'Verapamil',
    'Versed',
    'Verzenio',
    'VESIcare',
    'Viagra',
    'Vibramycin',
    'Vicodin',
    'Victoza',
    'Viibryd',
    'Vilazodone',
    'Vimpat',
    'Vincristine',
    'Vistaril',
    'Vitamin B12',
    'Vitamin C',
    'Vitamin D',
    'Vitamin D3',
    'Vitamin E',
    'Vivitrol',
    'Voltaren',
    'Voltaren Arthritis Pain Gel',
    'Vonjo',
    'Voriconazole',
    'Vortioxetine',
    'Vosevi',
    'Votrient',
    'Voydeya',
    'Vraylar',
    'Vyepti',
    'Vyndamax',
    'Vyvanse',
    'Wainua',
    'Wakix',
    'Wal-Zyr D',
    'Warfarin',
    'Wart Remover',
    'Water for Injection',
    'Wegovy',
    'Welchol',
    'Welireg',
    'Wellbutrin',
    'Wellbutrin SR',
    'Wellbutrin XL',
    'Westcort',
    'Westhroid',
    'White Mulberry',
    'Wild yam',
    'Willow Bark',
    'Winlevi',
    'Winrevair',
    'Witch Hazel',
    'Witch hazel topical',
    'Wixela Inhub',
    'Wormwood',
    'WP Thyroid',
    'Wynzora',
    'Wyost',
    'Xadago',
    'Xalatan',
    'Xanax',
    'Xanax XR',
    'Xarelto',
    'Xcopri',
    'Xdemvy',
    'Xeljanz',
    'Xeloda',
    'Xelstrym',
    'Xembify',
    'Xenical',
    'Xeomin',
    'Xerava',
    'Xermelo',
    'Xgeva',
    'Xhance',
    'Xiaflex',
    'Xifaxan',
    'Xigduo XR',
    'Xiidra',
    'Xofigo',
    'Xofluza',
    'Xolair',
    'Xopenex',
    'Xopenex HFA',
    'Xphozah',
    'Xpovio',
    'Xtampza ER',
    'Xtandi',
    'Xulane',
    'Xultophy',
    'XyliMelts',
    'Xylitol',
    'Xylocaine',
    'Xylocaine Jelly',
    'Xyosted',
    'Xyrem',
    'Xywav',
    'Xyzal',
    'Yarrow',
    'Yasmin',
    'Yaz',
    'Ycanth',
    'Yellow fever vaccine',
    'Yellow Root',
    'Yerba Santa',
    'Yervoy',
    'Yescarta',
    'YF-Vax',
    'Yohimbine',
    'Yondelis',
    'Yonsa',
    'Yosprala',
    'Yuflyma',
    'Yupelri',
    'Yusimry',
    'Yutiq',
    'Yuvafem',
    'Zaditor',
    'Zaleplon',
    'Zanaflex',
    'Zantac',
    'Zarxio',
    'Zavzpret',
    'Zebeta',
    'Zegalogue',
    'Zenpep',
    'Zepbound',
    'Zeposia',
    'Zestril',
    'Zetia',
    'Zidovudine',
    'Zilbrysq',
    'Zileuton',
    'Zinc',
    'Zinc gluconate',
    'Zinc sulfate',
    'Ziprasidone',
    'Zithromax',
    'Zocor',
    'Zofran',
    'Zofran ODT',
    'Zoladex',
    'Zoledronic acid',
    'Zolmitriptan',
    'Zoloft',
    'Zolpidem',
    'Zometa',
    'Zomig',
    'Zonisamide',
    'Zopiclone',
    'Zoryve',
    'Zosyn',
    'Zovirax',
    'Zydelig',
    'Zykadia',
    'Zyloprim',
    'Zynteglo',
    'Zyprexa',
    'Zyrtec',
    'Zytiga',
    'Zyvox',
  ];

  return medications;
}